exports.up = function(knex) {
    return knex.schema.createTable('cnpj_dados_cadastrais_pj', (table)=>{
        table.string('tipo_de_registro') 
        table.string('indicador') 
        table.string('tipo_atualizacao') 
        table.string('cnpj') 
        table.string('identificador_matriz_filial') 
        table.string('razao_social') 
        table.string('nome_fantasia') 
        table.string('situacao_cadastral') 
        table.string('data_situacao_cadastral') 
        table.string('motivo_situacao_cadastral') 
        table.string('nm_cidade_exterior') 
        table.string('cod_pais') 
        table.string('nm_pais') 
        table.string('codigo_natureza_juridica') 
        table.string('data_inicio_atividade') 
        table.string('cnae_fiscal') 
        table.string('descricao_tipo_logradouro') 
        table.string('logradouro') 
        table.string('numero') 
        table.string('complemento') 
        table.string('bairro') 
        table.string('cep') 
        table.string('uf') 
        table.string('codigo_municipio') 
        table.string('municipio') 
        table.string('ddd_telefone_1') 
        table.string('ddd_telefone_2') 
        table.string('ddd_fax') 
        table.string('correio_eletronico') 
        table.string('qualificacao_responsavel') 
        table.string('capital_social_empresa') 
        table.string('porte_empresa') 
        table.string('opcao_pelo_simples') 
        table.string('data_opcao_pelo_simples') 
        table.string('data_exclusao_simples') 
        table.string('opcao_pelo_mei') 
        table.string('situacao_especial') 
        table.string('data_situacao_especial') 
        table.string('filler') 
        table.string('fim_registro') 
    })
};

exports.down = function(knex) { 
    return knex.schema.dropTable('cnpj_dados_cadastrais_pj')
};

